### ISSUE TITLE
Remove env files from git control

### ISSUE THREAD

**Issue by radulucaciu** [jozsi/wealthor#40]
Commit 09fe4acb732a39783d51490c2b49e74c15fc04f5 added the env file under git control. Since this is customizable for each user, it should not be overridden by github. We should have an example file that each user can customize for their own application.

I know we have env.local that overrides this file, but we should not have anything specified by default (privacy issue)

**Comment by jozsi** [comment]
`.env` are the defaults. if you need to override some settings, just create a `.env.local` with they keys you want to change. Why?
- `.env` provides recommended defaults and allows the app to run out of the box (if the technical requirements are met, of course)
- whenever new environment/setting keys are added, it won't break your app; you don't need to hunt down the changelog/commit history to see why your app breaks after new commits

This was adopted by Facebook's `create-react-app`/`react-scripts`: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#what-other-env-files-are-can-be-used

**Comment by radulucaciu** [comment]
@jozsi I know, I mentioned it above. Yet, it's still not a good idea because it contains sensitive information and by default that should not be exposed since it's a security risk - in the future we might have additional variables in there - I am sure that a lot of people will not bother to change those, which could potentially give an intruder access with the default values. 

I'd rather have a setup script that creates the env file on the first run.

**Comment by jozsi** [comment]
I've removed `.env` from git control and renamed it to `.env.sample`. Added a fallback to `.env.sample` if `.env` exists (via 5a7951b), however it does not cover the tests (which will fail) because `jest` (the test runner) uses each test file as an entry point. So:
- we let tests fail if no `.env` is set
- try to include a common entry point for all tests
- we include the fallback in each test individually
- we do some hacking to [create-react-app/react-scripts' env.js](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/env.js#L28)

**Comment by jozsi** [comment]
I've spent more research on this. [dotenv](https://github.com/motdotla/dotenv#should-i-have-multiple-env-files) is strongly against having multiple environment files. So we'll stick to `.env` only (not committed) and provide a `.env.example` file. We use [dotenv-safe](https://github.com/rolodato/dotenv-safe) to validate that all fields exist in `.env`, otherwise the process exists with the list of missing fields.

Done via 80a7508d6e2706508e63af177f6b2351a0439ee1 & other commits
